apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-assignment-deployment
  labels:
    app: docker-assignment
spec:
  selector:
    matchLabels:
      app: docker-assignment
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-assignment
    spec:
      containers:
        - name: docker-assignment
          image: akash9993/docker-assignment:v1
          ports:
            - containerPort: 8000
